# docker-compose.yml
version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: yourusername
      POSTGRES_PASSWORD: yourpassword
      POSTGRES_DB: yourapp_development
    ports:
      - "5432:5432"  # Exposes PostgreSQL on localhost:5432

  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && rails s -b '0.0.0.0'"
    environment:
      DATABASE_HOST: db
      DATABASE_USER: yourusername
      DATABASE_PASSWORD: yourpassword
    volumes:
      - ".:/app"
    ports:
      - "3001:3000"  # Exposes Rails on localhost:3000
    depends_on:
      - db
